# Generated by Django 2.1.2 on 2018-10-20 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20181020_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('-fees',)},
        ),
    ]
