# Generated by Django 2.1.2 on 2018-10-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20181022_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='remaining_fees',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
