# Generated by Django 2.1.2 on 2018-10-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_student_remaining_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('partpayment', 'PartPayment'), ('fullpayment', 'FullPayment')], max_length=10, null=True),
        ),
    ]
