# Generated by Django 2.1.2 on 2018-10-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_student_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='remaining_fees_date',
            field=models.DateTimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('partpayment', 'PartPayment'), ('fullpayment', 'FullPayment')], max_length=100, null=True),
        ),
    ]
