# Generated by Django 2.1.2 on 2018-10-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20181022_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_status',
            field=models.CharField(blank=True, choices=[('Enquiary', 'Enquiary'), ('Registered', 'Register')], default='Enquiary', max_length=25, null=True),
        ),
    ]
