# Generated by Django 2.1.2 on 2018-10-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_student_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_status',
            field=models.CharField(blank=True, choices=[('Enquiary', 'Enquiary'), ('Registered', 'Register')], max_length=25, null=True),
        ),
    ]
