# Generated by Django 2.1.2 on 2018-10-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20181022_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_status',
            field=models.CharField(blank=True, choices=[('Enquiary', 'Enquiary'), ('Registered', 'Register')], default='Register', max_length=25, null=True),
        ),
    ]
