# Generated by Django 2.1.2 on 2018-10-23 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20181022_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enquiary_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='fees_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='remaining_fees_date',
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
    ]
