# Generated by Django 2.1.2 on 2018-10-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_auto_20181023_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=400),
        ),
    ]
