# Generated by Django 2.1.2 on 2018-11-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_auto_20181103_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('partpayment', 'PartPayment'), ('fullpayment', 'FullPayment')], max_length=100, null=True),
        ),
    ]
