# Generated by Django 2.1.3 on 2018-11-03 05:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_auto_20181103_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fees',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(code='Invalid number', message='Fees should be numeric value', regex='^\\d{4,5}$')]),
        ),
    ]
