# Generated by Django 2.1.3 on 2018-11-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_auto_20181103_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='text',
            new_name='address',
        ),
        migrations.AddField(
            model_name='student',
            name='mode_of_payment',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Online', 'Online')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('partpayment', 'PartPayment'), ('fullpayment', 'FullPayment')], max_length=100, null=True),
        ),
    ]
