# Generated by Django 2.1.3 on 2018-11-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_auto_20181104_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Partpayment', 'PartPayment'), ('fullpayment', 'FullPayment')], max_length=100, null=True),
        ),
    ]
