# Generated by Django 2.1.3 on 2018-11-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_auto_20181107_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Part Payment', 'PartPayment'), ('full Payment', 'FullPayment')], max_length=100, null=True),
        ),
    ]
