# Generated by Django 2.1.3 on 2018-11-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_auto_20181109_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Part Payment', 'Part Payment'), ('full Payment', 'Full Payment')], max_length=100, null=True),
        ),
    ]
